# Generated by Django 4.2.6 on 2023-11-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawfirm',
            name='registration_number',
        ),
    ]
