# Generated by Django 4.2.6 on 2023-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_institution_iso_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='registration_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
