# Generated by Django 4.2.6 on 2023-11-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_lawfirm_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawfirm',
            name='registration_number',
        ),
    ]
