# Generated by Django 4.2.6 on 2023-11-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_lawfirm_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='ISO_number',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='registration_number',
            field=models.CharField(default='687', max_length=50),
            preserve_default=False,
        ),
    ]
