# Generated by Django 4.2.5 on 2023-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawrisdb', '0002_caseruling_client_documenttemplate_invoice_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='case',
        ),
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='lawyers',
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='contact_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
