# Generated by Django 5.0.1 on 2024-01-07 13:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('affidavit', 'Affidavit'), ('petition', 'Petition'), ('plaint', 'Plaint'), ('notice of motion', 'Notice of Motion'), ('defense', 'Defense'), ('counter claim', 'Counter Claim'), ('judgment', 'Judgment')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category_of_law', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('commercial', 'Commercial'), ('land', 'Land'), ('arbitration', 'Arbitration'), ('family', 'Family'), ('business', 'Business'), ('property', 'Property')], max_length=20)),
                ('division_of_law', models.CharField(choices=[('family', 'Family'), ('land', 'Land'), ('employment', 'Employment'), ('tax', 'Tax'), ('intellectual property', 'Intellectual Property')], max_length=50)),
                ('sub_division', models.CharField(choices=[('succession', 'Succession'), ('divorce', 'Divorce'), ('real estate', 'Real Estate'), ('labor', 'Labor'), ('patent', 'Patent'), ('default', 'Default')], default='Default', max_length=20)),
                ('template_file_docx', models.CharField(max_length=255)),
                ('pdf_preview_file', models.CharField(default='preview_file', max_length=255)),
                ('form_fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
