# Generated by Django 4.2.5 on 2023-09-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('affidavit', 'Affidavit'), ('petition', 'Petition')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category_of_law', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal')], max_length=20)),
                ('division_of_law', models.CharField(choices=[('family', 'Family'), ('land', 'Land'), ('employment', 'Employment')], max_length=20)),
                ('branch_of_division_of_law', models.CharField(choices=[('succession', 'Succession')], max_length=20)),
                ('template_file', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='filled_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.template'),
        ),
    ]
